// Fallback slice for com.example.ArrayTest#testLoop(int[])
// Target line: 15
// Generated by WALA slicer fallback

    }
    
    public void testLoop(int[] data) {
        for (int i = 0; i < data.length; i++) {
            // This will also generate a warning
            int item = data[i];  // Line 15 - warning location
            processItem(item);
        }
    }
    
